/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoappmitienda;

import java.sql.Connection;
import java.util.List;

/**
 *
 * @author Felipe
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnRegProducto = new javax.swing.JButton();
        jBtnCategorias = new javax.swing.JButton();
        jBtnModProducto = new javax.swing.JButton();
        jBtnModPersona = new javax.swing.JButton();
        jBtnVerPedidos = new javax.swing.JButton();
        jBtnVerProductos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnMesa1 = new javax.swing.JButton();
        jBtnMesa2 = new javax.swing.JButton();
        jBtnMesa4 = new javax.swing.JButton();
        jBtnMesa3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));

        jBtnRegProducto.setBackground(new java.awt.Color(125, 93, 251));
        jBtnRegProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnRegProducto.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.PNG"))); // NOI18N
        jBtnRegProducto.setText("Registrar Producto");
        jBtnRegProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnRegProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnRegProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegProductoActionPerformed(evt);
            }
        });

        jBtnCategorias.setBackground(new java.awt.Color(125, 93, 251));
        jBtnCategorias.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.png"))); // NOI18N
        jBtnCategorias.setText("Categorias");
        jBtnCategorias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnCategorias.setIconTextGap(3);
        jBtnCategorias.setMargin(new java.awt.Insets(3, 14, 3, 10));
        jBtnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCategoriasActionPerformed(evt);
            }
        });

        jBtnModProducto.setBackground(new java.awt.Color(125, 93, 251));
        jBtnModProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnModProducto.setForeground(new java.awt.Color(255, 255, 255));
        jBtnModProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto-mod.png"))); // NOI18N
        jBtnModProducto.setText("Modificar Producto");
        jBtnModProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnModProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnModProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModProductoActionPerformed(evt);
            }
        });

        jBtnModPersona.setBackground(new java.awt.Color(125, 93, 251));
        jBtnModPersona.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnModPersona.setForeground(new java.awt.Color(255, 255, 255));
        jBtnModPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.PNG"))); // NOI18N
        jBtnModPersona.setText("Modificar Persona");
        jBtnModPersona.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnModPersona.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnModPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModPersonaActionPerformed(evt);
            }
        });

        jBtnVerPedidos.setBackground(new java.awt.Color(125, 93, 251));
        jBtnVerPedidos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnVerPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVerPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos.png"))); // NOI18N
        jBtnVerPedidos.setText("Ver Pedidos");
        jBtnVerPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnVerPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerPedidosActionPerformed(evt);
            }
        });

        jBtnVerProductos.setBackground(new java.awt.Color(125, 93, 251));
        jBtnVerProductos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnVerProductos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVerProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ver-productos.png"))); // NOI18N
        jBtnVerProductos.setText("Ver Productos");
        jBtnVerProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnVerProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtnRegProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnModProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnModPersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnVerPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jBtnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnModProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnModPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnVerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(125, 95, 219));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa - pque.PNG"))); // NOI18N
        jLabel1.setText(" Mesas");

        jBtnMesa1.setBackground(new java.awt.Color(125, 95, 219));
        jBtnMesa1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jBtnMesa1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.PNG"))); // NOI18N
        jBtnMesa1.setText("1");
        jBtnMesa1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jBtnMesa1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMesa1ActionPerformed(evt);
            }
        });

        jBtnMesa2.setBackground(new java.awt.Color(125, 95, 219));
        jBtnMesa2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jBtnMesa2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.PNG"))); // NOI18N
        jBtnMesa2.setText("2");
        jBtnMesa2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jBtnMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMesa2ActionPerformed(evt);
            }
        });

        jBtnMesa4.setBackground(new java.awt.Color(125, 95, 219));
        jBtnMesa4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jBtnMesa4.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.PNG"))); // NOI18N
        jBtnMesa4.setText("4");
        jBtnMesa4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jBtnMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMesa4ActionPerformed(evt);
            }
        });

        jBtnMesa3.setBackground(new java.awt.Color(125, 95, 219));
        jBtnMesa3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jBtnMesa3.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.PNG"))); // NOI18N
        jBtnMesa3.setText("3");
        jBtnMesa3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jBtnMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMesa3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMesa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegProductoActionPerformed
        new InterfazRegistrarProducto().setVisible(true);
    }//GEN-LAST:event_jBtnRegProductoActionPerformed

    private void jBtnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCategoriasActionPerformed
        new InterfazCategorias().setVisible(true);
    }//GEN-LAST:event_jBtnCategoriasActionPerformed

    private void jBtnModProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModProductoActionPerformed
        new InterfazModificarProducto().setVisible(true);
    }//GEN-LAST:event_jBtnModProductoActionPerformed

    private void jBtnModPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModPersonaActionPerformed
        new InterfazModificarPersona().setVisible(true);
    }//GEN-LAST:event_jBtnModPersonaActionPerformed

    private void jBtnVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerPedidosActionPerformed
        new InterfazMostrarPedidos().setVisible(true);
    }//GEN-LAST:event_jBtnVerPedidosActionPerformed

    private void jBtnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerProductosActionPerformed
        new InterfazMostrarProductos().setVisible(true);
    }//GEN-LAST:event_jBtnVerProductosActionPerformed

    private void jBtnMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMesa1ActionPerformed
        String nombreMesa = jBtnMesa1.getText();
        new InterfazMostrarMesa(nombreMesa).setVisible(true);
    }//GEN-LAST:event_jBtnMesa1ActionPerformed

    private void jBtnMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMesa2ActionPerformed
        String nombreMesa = jBtnMesa2.getText();
        new InterfazMostrarMesa(nombreMesa).setVisible(true);
    }//GEN-LAST:event_jBtnMesa2ActionPerformed

    private void jBtnMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMesa4ActionPerformed
        String nombreMesa = jBtnMesa4.getText();
        new InterfazMostrarMesa(nombreMesa).setVisible(true);
    }//GEN-LAST:event_jBtnMesa4ActionPerformed

    private void jBtnMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMesa3ActionPerformed
        String nombreMesa = jBtnMesa3.getText();
        new InterfazMostrarMesa(nombreMesa).setVisible(true);
    }//GEN-LAST:event_jBtnMesa3ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCategorias;
    private javax.swing.JButton jBtnMesa1;
    private javax.swing.JButton jBtnMesa2;
    private javax.swing.JButton jBtnMesa3;
    private javax.swing.JButton jBtnMesa4;
    private javax.swing.JButton jBtnModPersona;
    private javax.swing.JButton jBtnModProducto;
    private javax.swing.JButton jBtnRegProducto;
    private javax.swing.JButton jBtnVerPedidos;
    private javax.swing.JButton jBtnVerProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
