/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoappmitienda;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class InterfazEditarCategoria extends javax.swing.JFrame {

    Conexion con;
    Connection condb;
    CRUDSqlServer crud;
    List<Categoria> ListaCategorias;
    /**
     * Creates new form InterfazRegistrarProducto
     */
    public InterfazEditarCategoria() {
        initComponents();
        
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegProducto = new javax.swing.JPanel();
        jLblRegProducto = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jBtnActualizarCat = new javax.swing.JButton();
        jBtnEditarCategoria = new javax.swing.JButton();
        jBtnBuscarCat = new javax.swing.JButton();
        jBtnNuevaConsulta = new javax.swing.JButton();
        jBtnEliminarCat = new javax.swing.JButton();
        jLblNombreCat = new javax.swing.JLabel();
        jTxtFCategoria = new javax.swing.JTextField();
        jLblIdCategoria = new javax.swing.JLabel();
        jTxtFIdCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar categorias");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("JFrameRegProd"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jPanelRegProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jPanelRegProducto.setForeground(new java.awt.Color(51, 51, 51));
        jPanelRegProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLblRegProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLblRegProducto.setForeground(new java.awt.Color(125, 93, 251));
        jLblRegProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.png"))); // NOI18N
        jLblRegProducto.setText("Categorias");

        jLblNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNombre.setText("Nombre:");

        jTxtFNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTxtFNombre.setText("Nombre");
        jTxtFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFNombreMouseClicked(evt);
            }
        });

        jBtnActualizarCat.setBackground(new java.awt.Color(130, 113, 199));
        jBtnActualizarCat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnActualizarCat.setForeground(new java.awt.Color(255, 255, 255));
        jBtnActualizarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette.png"))); // NOI18N
        jBtnActualizarCat.setText("Guardar");
        jBtnActualizarCat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jBtnActualizarCat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnActualizarCat.setEnabled(false);
        jBtnActualizarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarCatActionPerformed(evt);
            }
        });

        jBtnEditarCategoria.setBackground(new java.awt.Color(125, 93, 251));
        jBtnEditarCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnEditarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jBtnEditarCategoria.setText("Editar");
        jBtnEditarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEditarCategoriaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnEditarCategoriaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnEditarCategoriaMouseReleased(evt);
            }
        });

        jBtnBuscarCat.setBackground(new java.awt.Color(125, 93, 251));
        jBtnBuscarCat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnBuscarCat.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBuscarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jBtnBuscarCat.setText("Buscar");
        jBtnBuscarCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBuscarCatMouseClicked(evt);
            }
        });
        jBtnBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarCatActionPerformed(evt);
            }
        });

        jBtnNuevaConsulta.setBackground(new java.awt.Color(130, 113, 199));
        jBtnNuevaConsulta.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnNuevaConsulta.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNuevaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jBtnNuevaConsulta.setText("Nueva consulta");
        jBtnNuevaConsulta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jBtnNuevaConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevaConsultaActionPerformed(evt);
            }
        });

        jBtnEliminarCat.setBackground(new java.awt.Color(130, 113, 199));
        jBtnEliminarCat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnEliminarCat.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEliminarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jBtnEliminarCat.setText("Eliminar");
        jBtnEliminarCat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jBtnEliminarCat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnEliminarCat.setEnabled(false);
        jBtnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarCatActionPerformed(evt);
            }
        });

        jLblNombreCat.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNombreCat.setText("Nombre:");

        jTxtFCategoria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTxtFCategoria.setText("Nombre");
        jTxtFCategoria.setDisabledTextColor(new java.awt.Color(125, 95, 219));
        jTxtFCategoria.setEnabled(false);
        jTxtFCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFCategoriaMouseClicked(evt);
            }
        });

        jLblIdCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblIdCategoria.setText("Id:");

        jTxtFIdCategoria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTxtFIdCategoria.setText("Id");
        jTxtFIdCategoria.setDisabledTextColor(new java.awt.Color(125, 95, 219));
        jTxtFIdCategoria.setEnabled(false);
        jTxtFIdCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFIdCategoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegProductoLayout = new javax.swing.GroupLayout(jPanelRegProducto);
        jPanelRegProducto.setLayout(jPanelRegProductoLayout);
        jPanelRegProductoLayout.setHorizontalGroup(
            jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                        .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblRegProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegProductoLayout.createSequentialGroup()
                        .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegProductoLayout.createSequentialGroup()
                                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                        .addComponent(jBtnBuscarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jBtnNuevaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblNombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFIdCategoria)
                                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                        .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtnEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(264, 264, 264))))
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jBtnActualizarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnEliminarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRegProductoLayout.setVerticalGroup(
            jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLblRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                        .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnBuscarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnNuevaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLblNombreCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                        .addComponent(jLblIdCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnActualizarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEliminarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jPanelRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //borra el texto predeterminado para poder ingresar el valor
    private void jTxtFNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFNombreMouseClicked
        if("Nombre".equals(jTxtFNombre.getText())){
            jTxtFNombre.setText("");
        }
    }//GEN-LAST:event_jTxtFNombreMouseClicked

    
    private void jBtnEditarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarCategoriaMouseClicked
        int opcion = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese la clave de administrador"));
        if(opcion== 1234){
            jTxtFCategoria.setEnabled(true);
            jBtnEliminarCat.setEnabled(true);
            jBtnActualizarCat.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Clave incorrecta");
        }
    }//GEN-LAST:event_jBtnEditarCategoriaMouseClicked

    private void jBtnEditarCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarCategoriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarCategoriaMousePressed

    private void jBtnEditarCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarCategoriaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarCategoriaMouseReleased

    private void jBtnBuscarCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarCatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscarCatMouseClicked

    
    //buscar el valor
    private void jBtnBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarCatActionPerformed
        //recibe el valor. Compara que no sea vacio
        String categoria = jTxtFNombre.getText().trim().toLowerCase();
        //si no es vacio, y no existe. Lo busca. Si lo es muestra mensaje
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
                
        if(!categoria.matches("") && !categoria.matches("nombre")){
            Categoria c = new Categoria();
            c.setNombre(categoria);
            c = crud.buscarCategoria(condb, c);
            jTxtFCategoria.setText(c.getNombre());
            jTxtFIdCategoria.setText(String.valueOf(c.getId()));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nombre ingresado no es válido. Intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnBuscarCatActionPerformed

    private void jBtnActualizarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarCatActionPerformed
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
             
        Categoria c = new Categoria();
        c.setId(Integer.parseInt(jTxtFIdCategoria.getText()));
        c.setNombre(jTxtFCategoria.getText().trim().toLowerCase());

        crud.actualizarCategoria(condb, c);
     
    }//GEN-LAST:event_jBtnActualizarCatActionPerformed

    private void jBtnNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevaConsultaActionPerformed
        limpiarCasillas();
    }//GEN-LAST:event_jBtnNuevaConsultaActionPerformed

    private void jBtnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarCatActionPerformed
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
        
        int idBorrar = Integer.parseInt(jTxtFIdCategoria.getText());
        Categoria c = new Categoria();
        c.setId(idBorrar);
        crud.eliminarCategoria(condb, c);
        limpiarCasillas();
        dispose();
        
        
    }//GEN-LAST:event_jBtnEliminarCatActionPerformed

    private void jTxtFCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFCategoriaMouseClicked

    private void jTxtFIdCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFIdCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFIdCategoriaMouseClicked

    private void limpiarCasillas(){
        jTxtFCategoria.setText("Categoria");
        jTxtFNombre.setText("Nombre");
        jTxtFIdCategoria.setText("");
        jTxtFCategoria.setEnabled(false);
        jTxtFIdCategoria.setEnabled(false);
        jBtnEliminarCat.setEnabled(false);
        jBtnActualizarCat.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarCat;
    private javax.swing.JButton jBtnBuscarCat;
    private javax.swing.JButton jBtnEditarCategoria;
    private javax.swing.JButton jBtnEliminarCat;
    private javax.swing.JButton jBtnNuevaConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblIdCategoria;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNombreCat;
    private javax.swing.JLabel jLblRegProducto;
    private javax.swing.JPanel jPanelRegProducto;
    private javax.swing.JTextField jTxtFCategoria;
    private javax.swing.JTextField jTxtFIdCategoria;
    private javax.swing.JTextField jTxtFNombre;
    // End of variables declaration//GEN-END:variables
}
