/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoappmitienda;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class InterfazRegistrarProducto extends javax.swing.JFrame {

    Conexion con;
    Connection condb;
    CRUDSqlServer crud;
    List<Categoria> ListaCategorias;
    /**
     * Creates new form InterfazRegistrarProducto
     */
    public InterfazRegistrarProducto() {
        initComponents();
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
        ListaCategorias = crud.obtenerCategorias(condb);
        cargarComboBox();
        
    }

    public void cargarComboBox(){
        for(Categoria categoria : ListaCategorias){
            jCBCategoria.addItem(categoria.getNombre());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegProducto = new javax.swing.JPanel();
        jLblRegProducto = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblCategoria = new javax.swing.JLabel();
        jLblPrecio = new javax.swing.JLabel();
        jLblUnidades = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jCBCategoria = new javax.swing.JComboBox<>();
        jTxtFPrecio = new javax.swing.JTextField();
        jSpnUnidades = new javax.swing.JSpinner();
        jBtnRegProducto = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnVerProductos = new javax.swing.JButton();
        jBtnModProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("JFrameRegProd"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jPanelRegProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jPanelRegProducto.setForeground(new java.awt.Color(51, 51, 51));
        jPanelRegProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLblRegProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLblRegProducto.setForeground(new java.awt.Color(125, 93, 251));
        jLblRegProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.PNG"))); // NOI18N
        jLblRegProducto.setText("Registrar Producto");

        jLblNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNombre.setText("Nombre:");

        jLblCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblCategoria.setText("Categoria:");

        jLblPrecio.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblPrecio.setText("Precio:");

        jLblUnidades.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblUnidades.setText("Unidades:");

        jTxtFNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTxtFNombre.setText("Nombre");
        jTxtFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFNombreMouseClicked(evt);
            }
        });

        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jTxtFPrecio.setText("Precio");
        jTxtFPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTxtFPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFPrecioMouseClicked(evt);
            }
        });
        jTxtFPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFPrecioActionPerformed(evt);
            }
        });
        jTxtFPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFPrecioKeyTyped(evt);
            }
        });

        jSpnUnidades.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jSpnUnidades.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jBtnRegProducto.setBackground(new java.awt.Color(125, 93, 251));
        jBtnRegProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnRegProducto.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette.png"))); // NOI18N
        jBtnRegProducto.setText("Registrar");
        jBtnRegProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRegProductoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnRegProductoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnRegProductoMouseReleased(evt);
            }
        });
        jBtnRegProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegProductoActionPerformed(evt);
            }
        });

        jBtnCancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(125, 93, 251));
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x-button.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegProductoLayout = new javax.swing.GroupLayout(jPanelRegProducto);
        jPanelRegProducto.setLayout(jPanelRegProductoLayout);
        jPanelRegProductoLayout.setHorizontalGroup(
            jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jBtnRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanelRegProductoLayout.setVerticalGroup(
            jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLblRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCategoria)
                    .addComponent(jLblPrecio)
                    .addComponent(jLblUnidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jBtnVerProductos.setBackground(new java.awt.Color(125, 93, 251));
        jBtnVerProductos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnVerProductos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVerProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ver-productos.png"))); // NOI18N
        jBtnVerProductos.setText("Ver Productos");
        jBtnVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerProductosActionPerformed(evt);
            }
        });

        jBtnModProducto.setBackground(new java.awt.Color(125, 93, 251));
        jBtnModProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnModProducto.setForeground(new java.awt.Color(255, 255, 255));
        jBtnModProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto-mod.png"))); // NOI18N
        jBtnModProducto.setText("Modificar producto");
        jBtnModProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModProductoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanelRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnVerProductos)
                .addGap(39, 39, 39)
                .addComponent(jBtnModProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVerProductos)
                    .addComponent(jBtnModProducto))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFPrecioActionPerformed

    private void jBtnRegProductoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegProductoMouseReleased
        
        
    }//GEN-LAST:event_jBtnRegProductoMouseReleased

    private void jBtnRegProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegProductoMouseClicked
       
    }//GEN-LAST:event_jBtnRegProductoMouseClicked

    private void jBtnRegProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegProductoMousePressed
        
    }//GEN-LAST:event_jBtnRegProductoMousePressed

    //borra el texto predeterminado para poder ingresar el valor
    private void jTxtFNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFNombreMouseClicked
        if("Nombre".equals(jTxtFNombre.getText())){
            jTxtFNombre.setText("");
        }
    }//GEN-LAST:event_jTxtFNombreMouseClicked

    private void jTxtFPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFPrecioMouseClicked
        if("Precio".equals(jTxtFPrecio.getText())){
            jTxtFPrecio.setText("");
        }
    }//GEN-LAST:event_jTxtFPrecioMouseClicked

    //revisa que la tecla ingresada
    private void jTxtFPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFPrecioKeyTyped
        char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume();  // Ignora si no es un número
            }
    }//GEN-LAST:event_jTxtFPrecioKeyTyped

    //pide confirmar si desea cancelar el registro, SI: borra, NO: ignora
    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        int opt = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea cancelar el registro?", "Cancelar Pedido", JOptionPane.YES_NO_OPTION);
        if(opt == 0){
            borrarDatos();
        }
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void borrarDatos(){
        jTxtFNombre.setText("Nombre");
        jCBCategoria.setSelectedIndex(0);
        jTxtFPrecio.setText("Precio");
        jSpnUnidades.setValue(0);
    }
    
    private void jBtnRegProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegProductoActionPerformed
        //try para validar info
        try{
            String nombre = jTxtFNombre.getText();
            String categoria = jCBCategoria.getSelectedItem().toString();
            System.out.println(categoria);
            int precio = Integer.parseInt(jTxtFPrecio.getText());
            int unidades = (int)jSpnUnidades.getValue();
            
            if((!nombre.matches("") && !nombre.matches("nombre"))&&(!categoria.matches("Seleccione"))&&(precio>0)){
                //almacernar variables
                Producto p = new Producto(nombre, precio, unidades, categoria);
                //ingresar con conexion
                crud.insertarProducto(condb, p);
                borrarDatos();
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Revise elementos e intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception ex)    {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_jBtnRegProductoActionPerformed

    private void jBtnModProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModProductoActionPerformed
        new InterfazModificarProducto().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnModProductoActionPerformed

    private void jBtnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerProductosActionPerformed
        new InterfazMostrarProductos().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnVerProductosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnModProducto;
    private javax.swing.JButton jBtnRegProducto;
    private javax.swing.JButton jBtnVerProductos;
    private javax.swing.JComboBox<String> jCBCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblCategoria;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblPrecio;
    private javax.swing.JLabel jLblRegProducto;
    private javax.swing.JLabel jLblUnidades;
    private javax.swing.JPanel jPanelRegProducto;
    private javax.swing.JSpinner jSpnUnidades;
    private javax.swing.JTextField jTxtFNombre;
    private javax.swing.JTextField jTxtFPrecio;
    // End of variables declaration//GEN-END:variables
}
