/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoappmitienda;

import java.sql.Connection;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class InterfazCategorias extends javax.swing.JFrame {

    Conexion con;
    Connection condb;
    CRUDSqlServer crud;
    List<Categoria> ListaCategorias;
    /**
     * Creates new form InterfazRegistrarProducto
     */
    public InterfazCategorias() {
        initComponents();
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
        ListaCategorias = crud.obtenerCategorias(condb);
        imprimirCategorias();
    }

    
    public void imprimirCategorias(){
        //defino el modelo de la tabla y le indico como se llama
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTCategorias.getModel();
        
        //Limpiar la tabla
        int i = 0;
        if(modelo.getRowCount()!=0){
            while(i!=-1){
                try{
                    modelo.removeRow(modelo.getRowCount()-1);
                }catch(Exception e){
                    i=-1;
                }
            }
        }
        try {
            
            List<Categoria> ListaC = ListaCategorias;
            Iterator<Categoria> it = ListaC.iterator();
            //como uso dos columnas el arreglo es de 2
            String [] obj = new String[2];
            while(it.hasNext()){
                Categoria c = it.next();
                obj[0] = String.valueOf(c.getId());
                obj[1] = c.getNombre();
                modelo.addRow(obj);
            }            
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegProducto = new javax.swing.JPanel();
        jLblRegProducto = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jBtnActualizarCat = new javax.swing.JButton();
        jBtnEditarCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCategorias = new javax.swing.JTable();
        jBtnRegCategoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("JFrameRegProd"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jPanelRegProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jPanelRegProducto.setForeground(new java.awt.Color(51, 51, 51));
        jPanelRegProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLblRegProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLblRegProducto.setForeground(new java.awt.Color(125, 93, 251));
        jLblRegProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.png"))); // NOI18N
        jLblRegProducto.setText("Categorias");

        jLblNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNombre.setText("Nombre:");

        jTxtFNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTxtFNombre.setText("Nombre");
        jTxtFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFNombreMouseClicked(evt);
            }
        });

        jBtnActualizarCat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnActualizarCat.setForeground(new java.awt.Color(125, 93, 251));
        jBtnActualizarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jBtnActualizarCat.setText("Actualizar lista");
        jBtnActualizarCat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jBtnActualizarCat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnActualizarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarCatActionPerformed(evt);
            }
        });

        jBtnEditarCategoria.setBackground(new java.awt.Color(125, 93, 251));
        jBtnEditarCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnEditarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jBtnEditarCategoria.setText("Editar");
        jBtnEditarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEditarCategoriaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnEditarCategoriaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnEditarCategoriaMouseReleased(evt);
            }
        });

        jTCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTCategorias);

        jBtnRegCategoria.setBackground(new java.awt.Color(125, 93, 251));
        jBtnRegCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnRegCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette.png"))); // NOI18N
        jBtnRegCategoria.setText("Registrar");
        jBtnRegCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRegCategoriaMouseClicked(evt);
            }
        });
        jBtnRegCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegProductoLayout = new javax.swing.GroupLayout(jPanelRegProducto);
        jPanelRegProducto.setLayout(jPanelRegProductoLayout);
        jPanelRegProductoLayout.setHorizontalGroup(
            jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                        .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblRegProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(342, 342, 342))
                    .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                        .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtFNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                                .addComponent(jBtnRegCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jBtnActualizarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jBtnEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(74, Short.MAX_VALUE))))
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRegProductoLayout.setVerticalGroup(
            jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegProductoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLblRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnActualizarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRegCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jPanelRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //borra el texto predeterminado para poder ingresar el valor
    private void jTxtFNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFNombreMouseClicked
        if("Nombre".equals(jTxtFNombre.getText())){
            jTxtFNombre.setText("");
        }
    }//GEN-LAST:event_jTxtFNombreMouseClicked

    
    private void jBtnEditarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarCategoriaMouseClicked
        new InterfazEditarCategoria().setVisible(true);
    }//GEN-LAST:event_jBtnEditarCategoriaMouseClicked

    private void jBtnEditarCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarCategoriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarCategoriaMousePressed

    private void jBtnEditarCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarCategoriaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarCategoriaMouseReleased

    private void jBtnRegCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegCategoriaMouseClicked

    private void jBtnRegCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegCategoriaActionPerformed
        //recibe el valor. Compara que no sea vacio
        String categoria = jTxtFNombre.getText().trim().toLowerCase();
        //si no es vacio, y no existe. Lo registra. Si lo es muestra mensaje
        
        if(!categoria.matches("") && !categoria.matches("nombre")){
            Categoria c = new Categoria();
            c.setNombre(categoria);
            crud.insertarCategoria(condb, c);
            //limpia el campo
           jTxtFNombre.setText("Nombre");
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nombre ingresado no es válido. Intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jBtnRegCategoriaActionPerformed

    private void jBtnActualizarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarCatActionPerformed
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
        ListaCategorias = crud.obtenerCategorias(condb);
        imprimirCategorias();
    }//GEN-LAST:event_jBtnActualizarCatActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarCat;
    private javax.swing.JButton jBtnEditarCategoria;
    private javax.swing.JButton jBtnRegCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblRegProducto;
    private javax.swing.JPanel jPanelRegProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCategorias;
    private javax.swing.JTextField jTxtFNombre;
    // End of variables declaration//GEN-END:variables
}
