/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoappmitienda;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class InterfazModificarPersona extends javax.swing.JFrame {

    Conexion con;
    Connection condb;
    CRUDSqlServer crud;
    Persona persona;
    String numeroOriginal;

    /**
     * Creates new form InterfazRegistrarProducto
     */
    public InterfazModificarPersona() {
        initComponents();
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelModPersona = new javax.swing.JPanel();
        jLblModPersona = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblTipoDNI = new javax.swing.JLabel();
        jLblNumero = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jCBTipoDNI = new javax.swing.JComboBox<>();
        jTxtFNumero = new javax.swing.JTextField();
        jBtnGuardarCambioPer = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLblApellido = new javax.swing.JLabel();
        jTxtFApellido = new javax.swing.JTextField();
        jBtnBuscarPersona = new javax.swing.JButton();
        jBtnEditarPersona = new javax.swing.JButton();
        jBtnEliminarPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("JFrameRegProd"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jPanelModPersona.setBackground(new java.awt.Color(255, 255, 255));
        jPanelModPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jPanelModPersona.setForeground(new java.awt.Color(51, 51, 51));
        jPanelModPersona.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLblModPersona.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLblModPersona.setForeground(new java.awt.Color(125, 93, 251));
        jLblModPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.PNG"))); // NOI18N
        jLblModPersona.setText("Modificar Persona");

        jLblNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNombre.setText("Nombre(s):");

        jLblTipoDNI.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblTipoDNI.setText("Tipo DNI:");

        jLblNumero.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNumero.setText("Numero:");

        jTxtFNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTxtFNombre.setText("Nombre");
        jTxtFNombre.setDisabledTextColor(new java.awt.Color(125, 95, 219));
        jTxtFNombre.setEnabled(false);
        jTxtFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFNombreMouseClicked(evt);
            }
        });

        jCBTipoDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE", "TI", "PA" }));

        jTxtFNumero.setText("Numero");
        jTxtFNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFNumeroMouseClicked(evt);
            }
        });
        jTxtFNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFNumeroActionPerformed(evt);
            }
        });
        jTxtFNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFNumeroKeyTyped(evt);
            }
        });

        jBtnGuardarCambioPer.setBackground(new java.awt.Color(125, 93, 251));
        jBtnGuardarCambioPer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnGuardarCambioPer.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardarCambioPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette.png"))); // NOI18N
        jBtnGuardarCambioPer.setText("Guardar");
        jBtnGuardarCambioPer.setEnabled(false);
        jBtnGuardarCambioPer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGuardarCambioPerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnGuardarCambioPerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnGuardarCambioPerMouseReleased(evt);
            }
        });
        jBtnGuardarCambioPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarCambioPerActionPerformed(evt);
            }
        });

        jBtnCancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(125, 93, 251));
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x-button.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 93, 251)));
        jBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLblApellido.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblApellido.setText("Apellido(s):");

        jTxtFApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTxtFApellido.setText("Apellido");
        jTxtFApellido.setDisabledTextColor(new java.awt.Color(125, 95, 219));
        jTxtFApellido.setEnabled(false);
        jTxtFApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFApellidoMouseClicked(evt);
            }
        });

        jBtnBuscarPersona.setBackground(new java.awt.Color(188, 177, 252));
        jBtnBuscarPersona.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnBuscarPersona.setForeground(new java.awt.Color(125, 93, 251));
        jBtnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jBtnBuscarPersona.setText("Buscar");
        jBtnBuscarPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 93, 251)));
        jBtnBuscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBuscarPersonaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBuscarPersonaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBuscarPersonaMouseReleased(evt);
            }
        });
        jBtnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarPersonaActionPerformed(evt);
            }
        });

        jBtnEditarPersona.setBackground(new java.awt.Color(188, 177, 252));
        jBtnEditarPersona.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnEditarPersona.setForeground(new java.awt.Color(125, 93, 251));
        jBtnEditarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jBtnEditarPersona.setText("Editar");
        jBtnEditarPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 93, 251)));
        jBtnEditarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEditarPersonaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnEditarPersonaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnEditarPersonaMouseReleased(evt);
            }
        });
        jBtnEditarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarPersonaActionPerformed(evt);
            }
        });

        jBtnEliminarPersona.setBackground(new java.awt.Color(125, 93, 251));
        jBtnEliminarPersona.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnEliminarPersona.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEliminarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jBtnEliminarPersona.setText("Eliminar");
        jBtnEliminarPersona.setEnabled(false);
        jBtnEliminarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEliminarPersonaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnEliminarPersonaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnEliminarPersonaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelModPersonaLayout = new javax.swing.GroupLayout(jPanelModPersona);
        jPanelModPersona.setLayout(jPanelModPersonaLayout);
        jPanelModPersonaLayout.setHorizontalGroup(
            jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnGuardarCambioPer, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnEliminarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                        .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFApellido)))
                    .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                        .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                                .addComponent(jTxtFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnEditarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLblModPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 44, Short.MAX_VALUE))
        );
        jPanelModPersonaLayout.setVerticalGroup(
            jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLblModPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTipoDNI)
                    .addComponent(jLblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEditarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                        .addComponent(jLblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModPersonaLayout.createSequentialGroup()
                        .addComponent(jLblApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanelModPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardarCambioPer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEliminarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanelModPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanelModPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFNumeroActionPerformed

    private void jBtnGuardarCambioPerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarCambioPerMouseReleased
        jBtnGuardarCambioPer.setBackground(new java.awt.Color(125, 93, 251));

    }//GEN-LAST:event_jBtnGuardarCambioPerMouseReleased

    private void jBtnGuardarCambioPerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarCambioPerMouseClicked

    }//GEN-LAST:event_jBtnGuardarCambioPerMouseClicked

    private void jBtnGuardarCambioPerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarCambioPerMousePressed
        jBtnGuardarCambioPer.setBackground(new java.awt.Color(188, 177, 252));
    }//GEN-LAST:event_jBtnGuardarCambioPerMousePressed

    private void jBtnBuscarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscarPersonaMouseClicked

    private void jBtnBuscarPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarPersonaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscarPersonaMousePressed

    private void jBtnBuscarPersonaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarPersonaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscarPersonaMouseReleased

    private void jTxtFNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFNumeroMouseClicked
        String nombre = jTxtFNumero.getText();
        if (nombre.matches("Numero")) {
            jTxtFNumero.setText("");
        }

    }//GEN-LAST:event_jTxtFNumeroMouseClicked

    private void jTxtFNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFNombreMouseClicked
        String nombre = jTxtFNombre.getText();
        if (nombre.matches("Nombre")) {
            jTxtFNombre.setText("");
        }
    }//GEN-LAST:event_jTxtFNombreMouseClicked

    private void jTxtFNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFNumeroKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();  // Ignora si no es un número
        }
    }//GEN-LAST:event_jTxtFNumeroKeyTyped

    private void jTxtFApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFApellidoMouseClicked
        String nombre = jTxtFApellido.getText();
        if (nombre.matches("Apellido")) {
            jTxtFApellido.setText("");
        }
    }//GEN-LAST:event_jTxtFApellidoMouseClicked

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        int opt = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea cancelar el registro?", "Cancelar Pedido", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            jTxtFNombre.setText("Nombre");
            jTxtFApellido.setText("Apellido");
            jTxtFNumero.setText("Numero");
            jCBTipoDNI.setSelectedIndex(0);
            jBtnGuardarCambioPer.setEnabled(false);
            jBtnEliminarPersona.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnEditarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarPersonaMouseClicked

    private void jBtnEditarPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarPersonaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarPersonaMousePressed

    private void jBtnEditarPersonaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarPersonaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarPersonaMouseReleased

    private void jBtnEliminarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarPersonaMouseClicked

    private void jBtnEliminarPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarPersonaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarPersonaMousePressed

    private void jBtnEliminarPersonaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarPersonaMouseReleased

        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
        crud.eliminarPersona(condb, numeroOriginal);


    }//GEN-LAST:event_jBtnEliminarPersonaMouseReleased

    //permite modificar las casillas para meter la info
    private void jBtnEditarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarPersonaActionPerformed
        numeroOriginal = jTxtFNumero.getText().trim();
        jBtnGuardarCambioPer.setEnabled(true);
        jBtnEliminarPersona.setEnabled(true);
        jTxtFNombre.setEnabled(true);
        jTxtFApellido.setEnabled(true);
    }//GEN-LAST:event_jBtnEditarPersonaActionPerformed

    private void jBtnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarPersonaActionPerformed
        String idTipo = jCBTipoDNI.getSelectedItem().toString();
        String idNumero = jTxtFNumero.getText().trim();

        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();

        if (!idNumero.matches("Numero") && !idNumero.matches("")) {
            Persona p = new Persona();
            p.setIdDNIPersona(idNumero);
            p.setTipoDNI(idTipo);
            p = crud.buscarPersona(condb, p);
            jTxtFApellido.setText(p.getApeliido());
            jTxtFNombre.setText(p.getNombre());
            

        } else {
            JOptionPane.showMessageDialog(rootPane, "Numero ingresado no es válido. Intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }

        


    }//GEN-LAST:event_jBtnBuscarPersonaActionPerformed

    private void jBtnGuardarCambioPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarCambioPerActionPerformed
        //recolecta la info
        String id = jTxtFNumero.getText();
        String nombre = jTxtFNombre.getText();
        String apellido = jTxtFApellido.getText();
        String tipoDNI = jCBTipoDNI.getSelectedItem().toString();

        //cambios
        if ((!nombre.matches("Seleccione") && !nombre.matches("Nombre")) && (!apellido.matches("Seleccione") && !apellido.matches("Aepllido"))) {
            persona = new Persona();
            persona.setNombre(nombre);
            persona.setApeliido(apellido);
            persona.setTipoDNI(tipoDNI);
            persona.setIdDNIPersona(id);

            crud.editarPersona(condb, persona, numeroOriginal);

            dispose();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Nombre ingresado no es válido. Intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnGuardarCambioPerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarPersona;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEditarPersona;
    private javax.swing.JButton jBtnEliminarPersona;
    private javax.swing.JButton jBtnGuardarCambioPer;
    private javax.swing.JComboBox<String> jCBTipoDNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblModPersona;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JLabel jLblTipoDNI;
    private javax.swing.JPanel jPanelModPersona;
    private javax.swing.JTextField jTxtFApellido;
    private javax.swing.JTextField jTxtFNombre;
    private javax.swing.JTextField jTxtFNumero;
    // End of variables declaration//GEN-END:variables
}
