/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoappmitienda;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class InterfazMostrarMesa extends javax.swing.JFrame {
    String nombreMesaI;
    Conexion con;
    Connection condb;
    CRUDSqlServer crud;
    List<Pedido> listaPedidos;
    List<Persona> listaPersonas;
    DefaultTableModel modeloPersonas;
    DefaultTableModel modeloPedidos;
    Grupo grupo;
        
    /**
     * Creates new form InterfazRegistrarProducto
     */
    public InterfazMostrarMesa(String nombreMesa) {
        nombreMesaI = nombreMesa;
        grupo = new Grupo();
        initComponents();
        jLblMostrarMesa.setText("Mesa " + nombreMesa);
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
        //consultar ultimo grupo y traer hora llegada
        grupo = crud.buscarGrupo(condb, nombreMesaI);
        modeloPersonas = (DefaultTableModel) jTPersonas.getModel();
//si es no es null solo crea el nuevo grupo en la mesa
        if(grupo.getHoraSalida()== null && grupo.getIdGrupo()==0){
            // crea el grupo y trae su numero para mostrarlo y listar
            grupo = crud.crearGrupo(condb, nombreMesaI);
            jLblGrupo.setText(String.valueOf(grupo.getIdGrupo()));
        }else{
            //trae pedidos y personas
            listaPedidos = crud.obtenerPedidosPorMesa(condb, Integer.parseInt(nombreMesa), grupo.getIdGrupo());
            imprimirPedidos();
            listaPersonas = crud.obtenerPersonasGrupo(condb,grupo.getIdGrupo());
            imprimirPersonas();
        }
        jLblGrupo.setText(String.valueOf(grupo.getIdGrupo()));
        
        
    }

    public void imprimirPedidos() {
        //defino el modelo de la tabla y le indico como se llama
        modeloPedidos = (DefaultTableModel) jTPedidos.getModel();

        //Limpiar la tabla
        int i = 0;
        if (modeloPedidos.getRowCount() != 0) {
            while (i != -1) {
                try {
                    modeloPedidos.removeRow(modeloPedidos.getRowCount() - 1);
                } catch (Exception e) {
                    i = -1;
                }
            }
        }
        try {

            List<Pedido> listaP = listaPedidos;
            Iterator<Pedido> it = listaP.iterator();
            //como uso 5 columnas el arreglo es de 5
            String[] obj = new String[5];
            while (it.hasNext()) {
                Pedido p = it.next();
                obj[0] = String.valueOf(p.getIdPedido());
                obj[1] = String.valueOf(p.getNombre());
                obj[2] = String.valueOf(p.getFechaPedido());
                obj[3] = String.valueOf(p.getEstado());
                if (p.getEstado() == 1) {
                    obj[3] = "Pagado";
                } else {
                    obj[3] = "Debe";
                }
                obj[4] = String.valueOf(p.getTotal());
                 

                modeloPedidos.addRow(obj);

            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }

    }
    
    
     public void imprimirPersonas() {
        //defino el modelo de la tabla y le indico como se llama
        

        //Limpiar la tabla
        int i = 0;
        if (modeloPersonas.getRowCount() != 0) {
            while (i != -1) {
                try {
                    modeloPersonas.removeRow(modeloPersonas.getRowCount() - 1);
                } catch (Exception e) {
                    i = -1;
                }
            }
        }
        try {

            List<Persona> listaP = listaPersonas;
            Iterator<Persona> it = listaP.iterator();
            //como uso 5 columnas el arreglo es de 5
            String[] obj = new String[4];
            while (it.hasNext()) {
                Persona p = it.next();
                obj[0] = p.getTipoDNI();
                obj[1] = p.getIdDNIPersona();
                obj[2] = p.getNombre();
                obj[3] = p.getApeliido();
                

                modeloPersonas.addRow(obj);

            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }

    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelMesaPersonas = new javax.swing.JPanel();
        jLblMostrarMesa = new javax.swing.JLabel();
        jLblPersonas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPersonas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLblGrupo = new javax.swing.JLabel();
        jBtnRegPedido = new javax.swing.JButton();
        jPanelMesaPedidos = new javax.swing.JPanel();
        jLblPedidos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTPedidos = new javax.swing.JTable();
        jBtnDetallePedido = new javax.swing.JButton();
        jBtnPedirCuenta = new javax.swing.JButton();
        jBtnAgregarPer = new javax.swing.JButton();
        jLblLogo = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("JFrameRegProd"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jPanelMesaPersonas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMesaPersonas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jPanelMesaPersonas.setForeground(new java.awt.Color(51, 51, 51));
        jPanelMesaPersonas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLblMostrarMesa.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLblMostrarMesa.setForeground(new java.awt.Color(125, 93, 251));
        jLblMostrarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa - pque.PNG"))); // NOI18N
        jLblMostrarMesa.setText("Mesa");

        jLblPersonas.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLblPersonas.setForeground(new java.awt.Color(102, 102, 102));
        jLblPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.PNG"))); // NOI18N
        jLblPersonas.setText("Personas");

        jTPersonas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo DNI", "Numero", "Nombre", "Apellido"
            }
        ));
        jScrollPane2.setViewportView(jTPersonas);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(125, 95, 219));
        jLabel2.setText("Grupo");

        jLblGrupo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLblGrupo.setForeground(new java.awt.Color(125, 95, 219));

        javax.swing.GroupLayout jPanelMesaPersonasLayout = new javax.swing.GroupLayout(jPanelMesaPersonas);
        jPanelMesaPersonas.setLayout(jPanelMesaPersonasLayout);
        jPanelMesaPersonasLayout.setHorizontalGroup(
            jPanelMesaPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesaPersonasLayout.createSequentialGroup()
                .addGroup(jPanelMesaPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMesaPersonasLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMesaPersonasLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelMesaPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMesaPersonasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLblPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMesaPersonasLayout.createSequentialGroup()
                                .addComponent(jLblMostrarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanelMesaPersonasLayout.setVerticalGroup(
            jPanelMesaPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesaPersonasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelMesaPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMostrarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblPersonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        jBtnRegPedido.setBackground(new java.awt.Color(125, 93, 251));
        jBtnRegPedido.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnRegPedido.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette.png"))); // NOI18N
        jBtnRegPedido.setText("Registrar Pedido");
        jBtnRegPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRegPedidoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnRegPedidoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnRegPedidoMouseReleased(evt);
            }
        });
        jBtnRegPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegPedidoActionPerformed(evt);
            }
        });

        jPanelMesaPedidos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMesaPedidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jPanelMesaPedidos.setForeground(new java.awt.Color(51, 51, 51));
        jPanelMesaPedidos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLblPedidos.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLblPedidos.setForeground(new java.awt.Color(102, 102, 102));
        jLblPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos.png"))); // NOI18N
        jLblPedidos.setText("Pedidos");

        jTPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero", "Persona", "Fecha", "Estado", "Total"
            }
        ));
        jScrollPane4.setViewportView(jTPedidos);

        jBtnDetallePedido.setBackground(new java.awt.Color(125, 93, 251));
        jBtnDetallePedido.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnDetallePedido.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDetallePedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registered-document.png"))); // NOI18N
        jBtnDetallePedido.setText("Detalle");
        jBtnDetallePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDetallePedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMesaPedidosLayout = new javax.swing.GroupLayout(jPanelMesaPedidos);
        jPanelMesaPedidos.setLayout(jPanelMesaPedidosLayout);
        jPanelMesaPedidosLayout.setHorizontalGroup(
            jPanelMesaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesaPedidosLayout.createSequentialGroup()
                .addGroup(jPanelMesaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelMesaPedidosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMesaPedidosLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLblPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnDetallePedido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMesaPedidosLayout.setVerticalGroup(
            jPanelMesaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesaPedidosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelMesaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDetallePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jBtnPedirCuenta.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnPedirCuenta.setForeground(new java.awt.Color(125, 93, 251));
        jBtnPedirCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registered-document.png"))); // NOI18N
        jBtnPedirCuenta.setText("Pedir Cuenta");
        jBtnPedirCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 93, 251)));
        jBtnPedirCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnPedirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPedirCuentaActionPerformed(evt);
            }
        });

        jBtnAgregarPer.setBackground(new java.awt.Color(125, 93, 251));
        jBtnAgregarPer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnAgregarPer.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAgregarPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.PNG"))); // NOI18N
        jBtnAgregarPer.setText("Agregar Persona");
        jBtnAgregarPer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 93, 251)));
        jBtnAgregarPer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarPerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAgregarPerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnAgregarPerMouseReleased(evt);
            }
        });
        jBtnAgregarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarPerActionPerformed(evt);
            }
        });

        jLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelMesaPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelMesaPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLblLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jBtnRegPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAgregarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPedirCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLblLogo)
                .addGap(18, 18, 18)
                .addComponent(jPanelMesaPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMesaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRegPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPedirCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegPedidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegPedidoMouseReleased
        jBtnRegPedido.setBackground(new java.awt.Color(125, 93, 251));
        
    }//GEN-LAST:event_jBtnRegPedidoMouseReleased

    private void jBtnRegPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegPedidoMouseClicked
       
    }//GEN-LAST:event_jBtnRegPedidoMouseClicked

    private void jBtnRegPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegPedidoMousePressed
        jBtnRegPedido.setBackground(new java.awt.Color(188, 177, 252));
    }//GEN-LAST:event_jBtnRegPedidoMousePressed

    private void jBtnAgregarPerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarPerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgregarPerMouseClicked

    private void jBtnAgregarPerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarPerMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgregarPerMousePressed

    private void jBtnAgregarPerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarPerMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgregarPerMouseReleased

    private void jBtnAgregarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarPerActionPerformed
        int numeroMesa = Integer.parseInt(nombreMesaI);
        String idGrupo = jLblGrupo.getText();
        new InterfazRegistrarPersona(numeroMesa,idGrupo).setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnAgregarPerActionPerformed

    private void jBtnRegPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegPedidoActionPerformed
        int numeroMesa = Integer.parseInt(nombreMesaI);
        String grupo = jLblGrupo.getText();
        new InterfazRegistrarPedido(numeroMesa, grupo, listaPersonas).setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnRegPedidoActionPerformed

    
    
    
    private void jBtnPedirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPedirCuentaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desean pedir la cuenta", "Pedir cuenta", JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            System.out.println("hi");
            crud = new CRUDSqlServer();
            crud.pedirCuenta(condb, jLblGrupo.getText());
            crud.cerrarGrupo(condb, jLblGrupo.getText());
            
        }
        dispose();
    }//GEN-LAST:event_jBtnPedirCuentaActionPerformed

    private void jBtnDetallePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDetallePedidoActionPerformed
        int filaPedido = jTPedidos.getSelectedRow();
        Object pedido = modeloPedidos.getValueAt(filaPedido, 0);
        Object mesa = jLblGrupo.getText();
        Object grupoAux = grupo.getIdGrupo();
        Object persona = modeloPedidos.getValueAt(filaPedido, 1);
        Object estado = modeloPedidos.getValueAt(filaPedido, 3);
        
        int pedidoAux = Integer.parseInt(pedido.toString());
        int mesaAux = Integer.parseInt(mesa.toString());
        int grupoAux2 = Integer.parseInt(mesa.toString());
        
        Pedido pedidoDetalle = new Pedido();
        pedidoDetalle.setIdPedido(pedidoAux);
        pedidoDetalle.setNombre(persona.toString());
        pedidoDetalle.setNumeroMesa(mesaAux);
        pedidoDetalle.setIdGrupo(grupoAux2);
        if(estado.toString().matches("Pagado")){
            pedidoDetalle.setEstado(1);
        }else{
            pedidoDetalle.setEstado(0);
        }
        
              
        new InterfazMostrarPedido(pedidoDetalle).setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnDetallePedidoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarPer;
    private javax.swing.JButton jBtnDetallePedido;
    private javax.swing.JButton jBtnPedirCuenta;
    private javax.swing.JButton jBtnRegPedido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblGrupo;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JLabel jLblMostrarMesa;
    private javax.swing.JLabel jLblPedidos;
    private javax.swing.JLabel jLblPersonas;
    private javax.swing.JPanel jPanelMesaPedidos;
    private javax.swing.JPanel jPanelMesaPersonas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTPedidos;
    private javax.swing.JTable jTPersonas;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
