/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoappmitienda;

import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class InterfazRegistrarPersona extends javax.swing.JFrame {

    Conexion con;
    Connection condb;
    CRUDSqlServer crud;
    List<TipoDNI> listaDocumentos;
    List<Mesa> listaMesas;
    String idGrupoI;

    /**
     * Creates new form InterfazRegistrarProducto
     */
    public InterfazRegistrarPersona(int numeroMesa, String numeroGrupo) {
        initComponents();
        con = new Conexion();
        condb = con.ObtenerConexion();
        crud = new CRUDSqlServer();
        cargarTiposDNI();
        idGrupoI = numeroGrupo;
        revisarMesas(numeroMesa);

    }

    public void cargarTiposDNI() {
        listaDocumentos = crud.obtenerTiposDNI(condb);
        jCBTipoDNI.removeAllItems();
        for (TipoDNI tipo : listaDocumentos) {
            jCBTipoDNI.addItem(String.valueOf(tipo.getTipoDNI()));
        }
    }

    public void revisarMesas(int mesaSeleccionada) {
        listaMesas = crud.obtenerMesas(condb);
        for (Mesa m : listaMesas) {
            jCBMesa.addItem(String.valueOf(m.getNumeroMesa()));
        }

        jCBMesa.setSelectedIndex(mesaSeleccionada);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegPersona = new javax.swing.JPanel();
        jLblRegPersona = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblTipoCategoria = new javax.swing.JLabel();
        jLblNumeroDNI = new javax.swing.JLabel();
        jLblMesa = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jCBTipoDNI = new javax.swing.JComboBox<>();
        jTxtFNumeroDNI = new javax.swing.JTextField();
        jBtnRegPersona = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLblApellido = new javax.swing.JLabel();
        jTxtFApellido = new javax.swing.JTextField();
        jCBMesa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("JFrameRegProd"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jPanelRegPersona.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 93, 251), 1, true));
        jPanelRegPersona.setForeground(new java.awt.Color(51, 51, 51));
        jPanelRegPersona.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLblRegPersona.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLblRegPersona.setForeground(new java.awt.Color(125, 93, 251));
        jLblRegPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.PNG"))); // NOI18N
        jLblRegPersona.setText("Registrar Persona");

        jLblNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNombre.setText("Nombre(s):");

        jLblTipoCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblTipoCategoria.setText("Tipo DNI:");

        jLblNumeroDNI.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblNumeroDNI.setText("Numero:");

        jLblMesa.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblMesa.setText("Mesa:");

        jTxtFNombre.setText("Nombre");
        jTxtFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFNombreMouseClicked(evt);
            }
        });

        jCBTipoDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE", "TI", "PA" }));

        jTxtFNumeroDNI.setText("Numero");
        jTxtFNumeroDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFNumeroDNIMouseClicked(evt);
            }
        });
        jTxtFNumeroDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFNumeroDNIActionPerformed(evt);
            }
        });
        jTxtFNumeroDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFNumeroDNIKeyTyped(evt);
            }
        });

        jBtnRegPersona.setBackground(new java.awt.Color(125, 93, 251));
        jBtnRegPersona.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnRegPersona.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette.png"))); // NOI18N
        jBtnRegPersona.setText("Registrar");
        jBtnRegPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRegPersonaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnRegPersonaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnRegPersonaMouseReleased(evt);
            }
        });
        jBtnRegPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegPersonaActionPerformed(evt);
            }
        });

        jBtnCancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(125, 93, 251));
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x-button.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 93, 251)));
        jBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLblApellido.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLblApellido.setText("Apellido(s):");

        jTxtFApellido.setText("Apellido");
        jTxtFApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtFApellidoMouseClicked(evt);
            }
        });

        jCBMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        javax.swing.GroupLayout jPanelRegPersonaLayout = new javax.swing.GroupLayout(jPanelRegPersona);
        jPanelRegPersona.setLayout(jPanelRegPersonaLayout);
        jPanelRegPersonaLayout.setHorizontalGroup(
            jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblTipoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(jLblMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))
                                    .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jCBMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLblRegPersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtFNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jLblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jBtnRegPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        jPanelRegPersonaLayout.setVerticalGroup(
            jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLblRegPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                        .addComponent(jLblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegPersonaLayout.createSequentialGroup()
                        .addComponent(jLblApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTipoCategoria)
                    .addComponent(jLblNumeroDNI)
                    .addComponent(jLblMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtFNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelRegPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRegPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanelRegPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanelRegPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFNumeroDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFNumeroDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFNumeroDNIActionPerformed

    private void jBtnRegPersonaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegPersonaMouseReleased
        jBtnRegPersona.setBackground(new java.awt.Color(125, 93, 251));

    }//GEN-LAST:event_jBtnRegPersonaMouseReleased

    private void jBtnRegPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegPersonaMouseClicked

    }//GEN-LAST:event_jBtnRegPersonaMouseClicked

    private void jBtnRegPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegPersonaMousePressed
        jBtnRegPersona.setBackground(new java.awt.Color(188, 177, 252));
    }//GEN-LAST:event_jBtnRegPersonaMousePressed

    private void jTxtFNumeroDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFNumeroDNIMouseClicked
        String nombre = jTxtFNumeroDNI.getText();
        if (nombre.matches("Numero")) {
            jTxtFNumeroDNI.setText("");
        }
    }//GEN-LAST:event_jTxtFNumeroDNIMouseClicked

    private void jTxtFNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFNombreMouseClicked
        String nombre = jTxtFNombre.getText();
        if (nombre.matches("Nombre")) {
            jTxtFNombre.setText("");
        }
    }//GEN-LAST:event_jTxtFNombreMouseClicked

    private void jTxtFApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtFApellidoMouseClicked
        String apellido = jTxtFApellido.getText();
        if (apellido.matches("Apellido")) {
            jTxtFApellido.setText("");
        }
    }//GEN-LAST:event_jTxtFApellidoMouseClicked

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        limpiarCasillas();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnRegPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegPersonaActionPerformed
        //try para validar info
        try {
            String nombre = jTxtFNombre.getText();
            String apellido = jTxtFApellido.getText();
            String tipoDNI = jCBTipoDNI.getSelectedItem().toString();
            String numero = jTxtFNumeroDNI.getText().trim();

            int numeroMesa = Integer.parseInt(jCBMesa.getSelectedItem().toString());

            if ((!nombre.matches("") && !nombre.matches("nombre")) && (!nombre.matches("") && !nombre.matches("nombre"))) {
                //almacernar variables
                Persona p = new Persona();
                p.setIdDNIPersona(numero);
                p.setNombre(nombre);
                p.setApeliido(apellido);
                p.setTipoDNI(tipoDNI);
                p.setNumeroMesa(numeroMesa);
               
                
                crud.registrarPersona(condb, p, idGrupoI);

                limpiarCasillas();
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Revise elementos e intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }


    }//GEN-LAST:event_jBtnRegPersonaActionPerformed

    private void jTxtFNumeroDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFNumeroDNIKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();  // Ignora si no es un número
        }
    }//GEN-LAST:event_jTxtFNumeroDNIKeyTyped

    public void limpiarCasillas() {
        jTxtFNombre.setText("Nombre");
        jTxtFApellido.setText("Apellido");
        jTxtFNumeroDNI.setText("Numero");
        jCBTipoDNI.setSelectedIndex(0);
        jCBMesa.addItem("Seleccione");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnRegPersona;
    private javax.swing.JComboBox<String> jCBMesa;
    private javax.swing.JComboBox<String> jCBTipoDNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblMesa;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNumeroDNI;
    private javax.swing.JLabel jLblRegPersona;
    private javax.swing.JLabel jLblTipoCategoria;
    private javax.swing.JPanel jPanelRegPersona;
    private javax.swing.JTextField jTxtFApellido;
    private javax.swing.JTextField jTxtFNombre;
    private javax.swing.JTextField jTxtFNumeroDNI;
    // End of variables declaration//GEN-END:variables
}
